server:
  #端口号
  port: 9999
  servlet:
    #项目访问路径
    context-path: /file

#分布式文件系统fastDfs配置
fdfs:
  #socket连接超时时长
  soTimeout: 1500
  #连接tracker服务器超时时长
  connectTimeout: 600
  resHost: 192.168.1.88
  storagePort: 80
  #缩略图生成参数，可选
  thumbImage:
    width: 150
    height: 150
  #TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port
  trackerList:
  - 192.168.1.88:22122

#thymelea模板配置
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  resources:
    static-locations: classpath:/resources/,classpath:/static/
  mvc:
    static-path-pattern: /**
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  #数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.88:3306/file?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: root
    #初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    #配置获取连接等待超时的时间
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  redis:
    #数据库索引
    database: 0
    host: 192.168.1.88
    port: 6379
    password: iamzkm180
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞时间(负数表示没有限制)
        max-wait: -1ms
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    timeout: 10000ms

#该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.file.model

#pageHelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
  page-size-zero: true

#日志打印级别
#logging:
#  file: springboot.log
#  level:
#    com.file.mapper: trace